name: Frontend CI - Build & Push Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatically on pushes to main branch
  push:
    branches:
      - main
    paths: # Only trigger if changes are in the frontend directory
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

# Define global environment variables that can be used across jobs
env:
  # Hardcoded ACR login server
  ACR_LOGIN_SERVER: sit722acrsimba01.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Azure login using GitHub Secret (secure)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Azure Container Registry (ACR)
    - name: Login to Azure Container Registry
      run: az acr login --name sit722acrsimba01

    # Build and Push Docker image for Frontend
    - name: Build and Push Frontend Image
      run: |
        docker build -t sit722acrsimba01.azurecr.io/frontend:latest ./frontend/
        docker push sit722acrsimba01.azurecr.io/frontend:latest

    # Logout from Azure for security
    - name: Logout from Azure
      run: az logout
      if: always()

